main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('tunes/', views.tunes_index, name='index'),
    path('tunes/<int:tune_id>/', views.tunes_detail, name='detail'),
    path('tunes/create/', views.TuneCreate.as_view(), name='tunes_create'),
    path('tunes/<int:pk>/update/', views.TuneUpdate.as_view(), name='tunes_update'),
    path('tunes/<int:pk>/delete/', views.TuneDelete.as_view(), name='tunes_delete'),
    path('tunes/<int:tune_id>/add_group/', views.add_group, name='add_group'),
    path('instruments/', views.InstrumentList.as_view(), name='instruments_index'),
    path('instruments/<int:pk>/', views.InstrumentDetail.as_view(), name='instruments_detail'),
    path('instruments/create/', views.InstrumentCreate.as_view(), name='instruments_create'),
    path('instruments/<int:pk>/update/', views.InstrumentUpdate.as_view(), name='instruments_update'),
    path('instruments/<int:pk>/delete/', views.InstrumentDelete.as_view(), name='instruments_delete'),
    path('tunes/<int:tune_id>/assoc_instrument/<int:instrument_id>/', views.assoc_instrument, name='assoc_instrument'),
    path('tunes/<int:tune_id>/unassoc_instrument/<int:instrument_id>/', views.unassoc_instrument, name='unassoc_instrument'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name='signup'),
]

tunecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),

]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
PLAYLIST = (
    ('C', 'Country'),
    ('R', 'Rock'),
    ('P', 'Pop'),
    ('H', 'HipHop'),
    ('M', 'Melody'),
)

class Instrument(models.Model):
    name = models.CharField(max_length=50)
    kind = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('instruments_detail', kwargs={'pk': self.id})

class Tune(models.Model):
    artist = models.CharField(max_length=100)
    song = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    length = models.IntegerField()
    instruments = models.ManyToManyField(Instrument)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.artist
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'tune_id': self.id})

class Group(models.Model):
    name = models.CharField(max_length=30)
    playlist = models.CharField(
        max_length=1,
        choices=PLAYLIST,
        default=PLAYLIST[0][0]
    )
    tune = models.ForeignKey(Tune, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_playlist_display()} on {self.name}"

main_app/forms.py
from django.forms import ModelForm
from .models import Group

class GroupForm(ModelForm):
  class Meta:
    model = Group
    fields = ['name', 'playlist']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Tune, Group, Instrument
from .forms import GroupForm


# Define the home view
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def tunes_index(request):
    tunes = Tune.objects.all()
    return render(request, 'tunes/index.html', { 'tunes': tunes })
@login_required
def tunes_detail(request, tune_id):
  tune = Tune.objects.get(id=tune_id)
  instruments_tune_doesnt_have = Instrument.objects.exclude(id__in = tune.instruments.all().values_list('id'))
  group_form = GroupForm()
  return render(request, 'tunes/detail.html', { 'tune': tune, 'group_form': group_form, 'instruments': instruments_tune_doesnt_have })

@login_required
def add_group(request, tune_id):
    form = GroupForm(request.POST)
    if form.is_valid():
        new_group = form.save(commit=False)
        new_group.tune_id = tune_id
        new_group.save()
    return redirect('detail', tune_id=tune_id)

@login_required
def assoc_instrument(request, tune_id, instrument_id):
  Tune.objects.get(id=tune_id).instruments.add(instrument_id)
  return redirect('detail', tune_id=tune_id)

@login_required
def unassoc_instrument(request, tune_id, instrument_id):
  Tune.objects.get(id=tune_id).instruments.remove(instrument_id)
  return redirect('detail', tune_id=tune_id)

class TuneCreate(LoginRequiredMixin, CreateView):
  model = Tune
  fields = '__all__'
  success_url = '/tunes/'

  def form_valid(self, form):
    form.instance.user = self.request.user  
    return super().form_valid(form)

class TuneUpdate(LoginRequiredMixin, UpdateView):
  model = Tune
  fields = ['song', 'genre', 'length']

class TuneDelete(LoginRequiredMixin, DeleteView):
  model = Tune
  success_url = '/tunes/'

class InstrumentList(LoginRequiredMixin, ListView):
  model = Instrument

class InstrumentDetail(LoginRequiredMixin, DetailView):
  model = Instrument

class InstrumentCreate(LoginRequiredMixin, CreateView):
  model = Instrument
  fields = '__all__'

class InstrumentUpdate(LoginRequiredMixin, UpdateView):
  model = Instrument
  fields = ['name', 'kind']

class InstrumentDelete(LoginRequiredMixin, DeleteView):
  model = Instrument
  success_url = '/instruments/'

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About the Tune Collector</h1>
<hr />
<p>Hire the Tune Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Tune Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;TuneCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
        {% if user.is_authenticated %}
          <li><a href="{% url 'tunes_create' %}">Add a Tune</a></li>
          <li><a href="{% url 'index' %}">View All My Tunes</a></li>
          <li><a href="{% url 'instruments_create' %}">Add an Instrument</a></li>
          <li><a href="{% url 'instruments_index' %}">View All Instruments</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
        {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Log In</a></li>
        {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Tune Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/instrument_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Instrument</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'instruments_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/instrument_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Instrument Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ instrument.name }}</span>
        <p>Type: {{ instrument.kind }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'instruments_update' instrument.id %}">Edit</a>
        <a href="{% url 'instruments_delete' instrument.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/instrument_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Instrument</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/instrument_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Instrument List</h1>

{% for instrument in instrument_list %}
  <a href="{% url 'instruments_detail' instrument.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ instrument.name }}</span>
            <p>Type: {{ instrument.kind }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/tune_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Tune</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.artist }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' tune.id %}" class="btn">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/tune_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.artist}}</span></h1>
  {% else %}
    <h1>Add Tune</h1>
{% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/tunes/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Tune Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ tune.artist }}</span>
        <p>Song: {{ tune.song }}</p>
        <p>Genre: {{ tune.genre }}</p>
        <p>Length: {{ tune.length }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'tunes_update' tune.id %}">Edit</a>
        <a href="{% url 'tunes_delete' tune.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
     <form action="{% url 'add_group' tune.id %}" method="post">
        {% csrf_token %}
        {{ group_form.as_p }}
        <input type="submit" class="btn" value="Add Group">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Name</th><th>Playlist</th></tr>
      </thead>
      <tbody>
        {% for group in tune.group_set.all %}
          <tr>
            <td>{{group.name}}</td>
            <td>{{group.get_playlist_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>Instruments</h3>
    {% if tune.instruments.count %}
      {% for instrument in tune.instruments.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A {{ instrument.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Instruments :(</h5>
    {% endif %}
  </div>
    <div class="col s6">
    <h3>Available Instruments</h3>
    {% if instruments.count %}
      {% for instrument in instruments.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A {{ toy.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_instrument' tune.id instrument.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{tune.artist}} Already Has All Instruments Available</h5>
    {% endif %}
  </div>
<script>
  var selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/tunes/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Tune List</h1>

{% for tune in tunes %}
  <div class="card">
  <a href="{% url 'detail' tune.id %}">
    <div class="card-content">
        <span class="card-title">{{ tune.artist }}</span>
        <p>Song: {{ tune.song }}</p>
        <p>Genre: {{ tune.genre }}</p>
        <p>Length: {{ tune.length }}</p>
        </div>
    </a>
  </div>
{% endfor %}

{% endblock %}